### ISSUE TITLE
 sql statement in getJourneyPatterns

### ISSUE THREAD

**Issue by cabanana** [aamalik/dinoToGtfsVRR#1]
Hi, 
I tried the same thing with the AVV importer and realized that the second sql statement in getJourneyPatterns  (dino.py) takes ridiculously long, doesn't it ?
Is there something wrong in my setup or did you go with it?

**Comment by yar-malik** [comment]
Hi, I think something might be wrong with your setup. 
I ran it last week and it was not slow for me.

**Comment by yar-malik** [comment]
Tell me if you dont manage to do it. I could help you out

**Comment by cabanana** [comment]
Thanks for answering and thanks for the offer.

Well, after setting up the data in a more reasonable way it ran through.
I've already seen that the stops are little bit messed up but i don't have an overview yet.

Is your restulting gtfs data fine or did you do some postprocessing ?

**Comment by yar-malik** [comment]
Hi, 
I did not do much postprocessing. What do you think is wrong. 
I did a manual review and things looked fine. In my opinion. 

Why do you think stops are messed up for you?

**Comment by aamalik** [comment]
@cabanana ?

**Comment by yar-malik** [comment]
@cabanana ?

**Comment by cabanana** [comment]
Sorry, I'm not working on it right now.
It was the splitting of the stop locations that got me confused. 
However, using the bliksemlabs script seem to work.
Thanks for your comments!
